/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/344d1fe8-71e6-438b-9184-03fceb709063 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float ET;
  CloudTemperatureSensor temperature;
  CloudPercentage soilMoisture;
  CloudRelativeHumidity humidity;
  bool manual_Watering;
  CloudTime upTime;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}
const char *deli =" ";

void loop() {
  ArduinoCloud.update();
  
  if (Serial.available() > 0 ) {
    String data = Serial.readStringUntil('\n'); //Read String until end of line
    const char* cdata = data.c_str(); //Convert string to array of characters
    char * strdata = strdup(cdata); //Duplicate the array
    char *ctemperature = strtok(strdata, deli); //Split the array until 1st space
    char *chumidity = strtok(NULL, deli); //2nd space
    char *csoilMoisture = strtok(NULL, deli); //3rd space
    char *cET = strtok(NULL, deli); //4th space
    char *cUpTime = strtok(NULL, deli); //5th space
    //Convert characters to floats
    temperature = atof(ctemperature); 
    humidity = atof(chumidity);
    soilMoisture = atof(csoilMoisture);
    ET = atof(cET);
    upTime = atof(cUpTime);
  }
}

/*
  Since ManualWatering is READ_WRITE variable, onManualWateringChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onManualWateringChange()  {
  // Add your code here to act upon ManualWatering change
  if (manual_Watering){
    Serial.print("MANUAL WATERING");
  }
}